name: player_premium
description: A premium IPTV Player application with TV-first experience.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Styling
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1
  responsive_sizer: ^3.3.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1

  # State Management
  flutter_bloc: ^8.1.6
  get: ^4.6.6

  # Utilities
  intl: ^0.20.2
  get_storage: ^2.1.1
  wakelock_plus: ^1.2.8
  filling_slider: ^0.0.3

  volume_controller: ^2.0.8


  #M3U   # Media Player

  # Media Player

  pod_player: ^0.2.2

  # Media Kit
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4


  # Networking
  dio: ^5.6.0

dependency_overrides:
  win32: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
